# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "{ datagoodie }"
title_separator: "|"
name: "Richard Rich Steinmetz"
email: "steinmetz.richard [- @ -] outlook.com"
description: >- # this means to ignore newlines until "baseurl:"
  A blog about data engineering, web-scraping, data in general, text analysis, text mining,
  data for social good purpose, machine learning, autonomous driving
  and software development.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://datagoodie.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: "RichStone/richstone.github.io"

twitter:
  username               : &twitter "stonerichio"
facebook:
  username               : &facebook "100008682485866"
  app_id                 :
  publisher              :

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
  - "https://twitter.com/stonerichio"
  - "https://www.facebook.com/profile.php?id=100008682485866"
  - "https://www.linkedin.com/in/richard-steinmetz/"
  - "https://plus.google.com/113275668565108530267"

author:
  name            : "Richard Rich Steinmetz"
  avatar          : "/assets/images/bio-photo.jpg"
  linkedin        : "richard-steinmetz"
  github          : "RichStone"
  stackoverflow   : "5925094/richard-rich-steinmetz"
  facebook        : *facebook
  twitter         : *twitter
  bio             : "Exploring the Universe of Data."
  email           : "steinmetz.richard [- @ -] outlook.com"
  home            : "/about/"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-archives

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: false
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: math
    values:
      layout: single
      author_profile: false
      share: true
      read_time: false

comments:
  provider: "disqus"
  disqus:
    shortname: "datagooide"

teaser: /assets/images/bio-photo.jpg

collections:
  math:
    output: true
    permalink: /:collection/:path/


search: true
search_full_content: true

paginate: 7 # amount of posts to show
paginate_path: /page:num/

include: ["_pages"]

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-124363106-1"
    anonymize_ip: false # default

bing_site_verification: "058B0E0F2FD021CEA13EF28D9980E564"


category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
